// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGdkyWghIH05yWKuxK0VHRQYdnq_52gg',
    appId: '1:83285692536:web:2d19fb88bedb2eee899d8d',
    messagingSenderId: '83285692536',
    projectId: 'amrajajabor-c97b7',
    authDomain: 'amrajajabor-c97b7.firebaseapp.com',
    storageBucket: 'amrajajabor-c97b7.firebasestorage.app',
    measurementId: 'G-C4Z33VHKFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuA_Hcb9MldbMVnUocrn4VDILjq0BLkE',
    appId: '1:83285692536:android:2eecb063f088c619899d8d',
    messagingSenderId: '83285692536',
    projectId: 'amrajajabor-c97b7',
    storageBucket: 'amrajajabor-c97b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXyizjwJVgOIRSPXxOM210JCKod5geq8',
    appId: '1:83285692536:ios:18ca666d0cee03d3899d8d',
    messagingSenderId: '83285692536',
    projectId: 'amrajajabor-c97b7',
    storageBucket: 'amrajajabor-c97b7.firebasestorage.app',
    iosBundleId: 'com.amrajajabor.amrajajaborMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgXyizjwJVgOIRSPXxOM210JCKod5geq8',
    appId: '1:83285692536:ios:18ca666d0cee03d3899d8d',
    messagingSenderId: '83285692536',
    projectId: 'amrajajabor-c97b7',
    storageBucket: 'amrajajabor-c97b7.firebasestorage.app',
    iosBundleId: 'com.amrajajabor.amrajajaborMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAGdkyWghIH05yWKuxK0VHRQYdnq_52gg',
    appId: '1:83285692536:web:34b6263e1d623b98899d8d',
    messagingSenderId: '83285692536',
    projectId: 'amrajajabor-c97b7',
    authDomain: 'amrajajabor-c97b7.firebaseapp.com',
    storageBucket: 'amrajajabor-c97b7.firebasestorage.app',
    measurementId: 'G-R7T47X94L4',
  );
}
